#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By header
apt-get update -y
apt-get install nginx -y

HOSTNAME=$(hostname)

echo "Holberton School" > /var/www/html/index.html

sed -i "s|server_name _;|server_name _;\n\tadd_header X-Served-By $HOSTNAME;|" /etc/nginx/sites-enabled/default

service nginx restart
