#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7023-web-01 54.211.178.57:80 check
    server 7023-web-02 WEB02_IP:80 check
EOF

service haproxy restart
