#!/usr/bin/env bash
# Installs and configures Nginx to listen on port 80 and return a page containing Holberton School
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.html
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

nginx -t
service nginx start
service nginx reload
</parameter>
