#!/usr/bin/env bash
# Installs and configures Nginx to listen on port 80 and return a page containing Holberton School
apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html
echo 'Holberton School for the win!' | tee /var/www/html/index.html /var/www/html/index.nginx-debian.html

service nginx start
