#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page with Ceci n'est pas une page
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-enabled/default

sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;|' /etc/nginx/sites-enabled/default

service nginx restart
