#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing Ceci n'est pas une page
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.html
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sed -i '/server_name _;/a \\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx start
service nginx reload
